# Generated by Django 3.2.2 on 2021-05-15 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
